# Use an official Python runtime as a parent image
FROM python:3.9-slim

ADD app.py .



# Install any needed dependencies specified in requirements.txt
#RUN pip install --no-cache-dir -r requirements.txt

# Run the application when the container launches
CMD ["python", "./app.py"]
